/**
 * Terms of Service Page
 * Legal terms and conditions for using KindleWood Studio
 */

import Link from 'next/link';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50">
      <div className="max-w-4xl mx-auto px-4 py-12">
        {/* Header */}
        <div className="text-center mb-12">
          <Link href="/" className="inline-block text-3xl font-bold mb-4 hover:opacity-80 transition-opacity">
            📚 Kindle<span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">Wood</span> Studio ✨
          </Link>
          <h1 className="text-4xl font-bold text-gray-900 mt-4">Terms of Service</h1>
          <p className="text-gray-600 mt-2">Last updated: October 25, 2025</p>
        </div>

        {/* Content */}
        <div className="bg-white rounded-2xl shadow-xl p-8 space-y-8">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Agreement to Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              By accessing or using KindleWood Studio, you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Service Description</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              KindleWood Studio is a personalized children's storybook generation platform that uses AI to
              create custom illustrated stories featuring your uploaded characters.
            </p>
            <div className="bg-blue-50 rounded-lg p-4 border-2 border-blue-200">
              <p className="text-gray-700">
                <strong>Beta Notice:</strong> KindleWood Studio is currently in BETA. Features, pricing,
                and availability may change without notice.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Account Requirements</h2>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>You must be at least 18 years old to create an account</li>
              <li>You must provide accurate and complete information</li>
              <li>You are responsible for maintaining account security</li>
              <li>One account per person; no account sharing</li>
              <li>You must comply with all applicable laws</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Acceptable Use</h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-2">You May:</h3>
                <ul className="list-disc list-inside text-gray-700 space-y-1 ml-4">
                  <li>Create personalized storybooks for personal use</li>
                  <li>Share your stories publicly or keep them private</li>
                  <li>Upload photos of family members with appropriate consent</li>
                  <li>Download and print your generated stories</li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-2">You May NOT:</h3>
                <ul className="list-disc list-inside text-gray-700 space-y-1 ml-4">
                  <li>Upload photos of others without their permission</li>
                  <li>Create inappropriate, offensive, or harmful content</li>
                  <li>Use the service for commercial purposes without authorization</li>
                  <li>Attempt to hack, abuse, or disrupt the service</li>
                  <li>Scrape, copy, or redistribute our AI models or code</li>
                  <li>Violate any applicable laws or regulations</li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Content & Intellectual Property</h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-2">Your Content</h3>
                <p className="text-gray-700">
                  You retain ownership of photos and content you upload. By using KindleWood Studio, you grant
                  us a limited license to process your content for service delivery (generating images,
                  storing stories, etc.).
                </p>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-2">Generated Content</h3>
                <p className="text-gray-700">
                  You own the stories and images generated by KindleWood Studio. However, similar outputs may be
                  generated for other users due to the nature of AI. We cannot guarantee uniqueness.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-2">Public Stories</h3>
                <p className="text-gray-700">
                  If you set a story to "public", you grant KindleWood Studio permission to display it on our
                  website and marketing materials. You can change visibility at any time.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Trial & Subscription Plans</h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-2">Free Trial</h3>
                <ul className="list-disc list-inside text-gray-700 space-y-1 ml-4">
                  <li>Duration: 7 days from signup</li>
                  <li>Limit: Up to 2 stories total</li>
                  <li>No credit card required</li>
                  <li>Full access to all features during trial</li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-2">Paid Subscription Plans</h3>
                <ul className="list-disc list-inside text-gray-700 space-y-1 ml-4">
                  <li><strong>Basic:</strong> $8.99/month or $89/year - 20 new stories per month</li>
                  <li><strong>Premium:</strong> $14.99/month or $149/year - Unlimited stories</li>
                  <li><strong>Team:</strong> $59.99/month or $599/year - 5 separate accounts, unlimited stories each</li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-2">Billing & Payments</h3>
                <ul className="list-disc list-inside text-gray-700 space-y-1 ml-4">
                  <li>All payments processed securely through Stripe</li>
                  <li>Subscriptions automatically renew unless cancelled</li>
                  <li>You may cancel at any time - access continues until end of billing period</li>
                  <li>Refunds handled on a case-by-case basis within 7 days of charge</li>
                  <li>Plan changes (upgrades/downgrades) are prorated immediately</li>
                  <li>We reserve the right to modify pricing with 30 days notice to existing subscribers</li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">KindleWood Kids App & COPPA Compliance</h2>
            <div className="space-y-4">
              <div className="bg-purple-50 border-2 border-purple-200 rounded-lg p-4">
                <h3 className="font-bold text-gray-900 mb-2">Children's Privacy Protection</h3>
                <p className="text-gray-700">
                  KindleWood complies with the Children's Online Privacy Protection Act (COPPA).
                  By using our services, you acknowledge and agree to the following:
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-2">Age Requirement</h3>
                <ul className="list-disc list-inside text-gray-700 space-y-1 ml-4">
                  <li>You must be at least 18 years old to create a KindleWood account</li>
                  <li>Parents/guardians are responsible for all child profiles created under their account</li>
                  <li>Children under 13 may only use the KindleWood Kids app with parental setup and supervision</li>
                </ul>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-2">Parental Consent</h3>
                <p className="text-gray-700">
                  By creating a child profile, you represent that you are the parent or legal guardian of the child
                  and consent to the collection and use of the child's information as described in our Privacy Policy.
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-gray-800 mb-2">KindleWood Kids App Usage</h3>
                <p className="text-gray-700">
                  The KindleWood Kids mobile app is designed for children to read stories created by their parents.
                  All content must be set up by a parent through KindleWood Studio before being accessible in the Kids app.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Service Availability</h2>
            <p className="text-gray-700 mb-4">
              We strive for high availability but cannot guarantee uninterrupted service. We may:
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>Perform maintenance with or without notice</li>
              <li>Modify or discontinue features</li>
              <li>Impose usage limits to prevent abuse</li>
              <li>Suspend accounts that violate these terms</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Disclaimer of Warranties</h2>
            <div className="bg-yellow-50 rounded-lg p-4 border-2 border-yellow-200">
              <p className="text-gray-700">
                KindleWood Studio is provided "AS IS" without warranties of any kind. We do not guarantee
                accuracy, reliability, or fitness for any particular purpose. AI-generated content
                may contain errors or inconsistencies.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Limitation of Liability</h2>
            <p className="text-gray-700">
              To the maximum extent permitted by law, KindleWood Studio shall not be liable for any indirect,
              incidental, special, or consequential damages arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Termination</h2>
            <p className="text-gray-700 mb-4">
              Either party may terminate this agreement:
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>You may delete your account at any time</li>
              <li>We may suspend or terminate accounts that violate these terms</li>
              <li>We may discontinue the service with reasonable notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Changes to Terms</h2>
            <p className="text-gray-700">
              We may modify these terms at any time. Continued use of the service after changes
              constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Governing Law</h2>
            <p className="text-gray-700">
              These terms are governed by the laws of the State of California, United States.
              Any disputes will be resolved in the state or federal courts located in California.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact Us</h2>
            <p className="text-gray-700">
              Questions about these Terms of Service?
            </p>
            <div className="bg-gray-50 rounded-lg p-4 mt-4">
              <p className="text-gray-700">
                <strong>Email:</strong> <a href="mailto:Admin@KindleWoodStudio.ai" className="text-blue-600 hover:text-blue-700 underline">Admin@KindleWoodStudio.ai</a>
              </p>
            </div>
          </section>
        </div>

        {/* Back Button */}
        <div className="text-center mt-8">
          <Link
            href="/"
            className="inline-block px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-lg font-medium hover:from-blue-700 hover:to-purple-700 transition-all shadow-md"
          >
            Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
