-- Add sketch_image_url column to character_library table
-- This stores the simple sketch drawing guide generated by Gemini

ALTER TABLE character_library
ADD COLUMN sketch_image_url TEXT;

COMMENT ON COLUMN character_library.sketch_image_url IS 'URL to the simple sketch drawing guide image (base64 data URL or storage URL)';
